import type { SubscriptionCatalogPort, SubscriptionModule } from '@/lib/domain/subscription';

const modules: SubscriptionModule[] = [
  { id: 'pms', category: 'operations', price: 39, includedIn: ['starter', 'growth', 'scale'], name: { en: 'Property management', de: 'Hotelverwaltung', ru: 'Управление отелем' } },
  { id: 'front-desk', category: 'operations', price: 29, includedIn: ['growth', 'scale'], name: { en: 'Front desk', de: 'Rezeption', ru: 'Фронт-деск' } },
  { id: 'accounting', category: 'operations', price: 29, includedIn: [], name: { en: 'Accounting and reporting', de: 'Buchhaltung und Berichte', ru: 'Бухгалтерия и отчёты' } },
  { id: 'housekeeping', category: 'operations', price: 19, includedIn: [], name: { en: 'Housekeeping', de: 'Housekeeping', ru: 'Уборка номеров' } },
  { id: 'orders', category: 'operations', price: 15, includedIn: [], name: { en: 'Services and food orders', de: 'Service- und Essensbestellungen', ru: 'Услуги и заказы еды' } },
  { id: 'booking-engine', category: 'distribution', price: 29, includedIn: ['starter', 'growth', 'scale'], name: { en: 'Direct booking engine', de: 'Direktbuchung', ru: 'Прямое бронирование' } },
  { id: 'channels', category: 'distribution', price: 39, includedIn: ['scale'], name: { en: 'Channel manager', de: 'Channel Manager', ru: 'Менеджер каналов' } },
  { id: 'rates', category: 'distribution', price: 25, includedIn: [], name: { en: 'Rate management', de: 'Preisverwaltung', ru: 'Управление тарифами' } },
  { id: 'communications', category: 'guest', price: 19, includedIn: [], name: { en: 'Guest communications', de: 'Gästekommunikation', ru: 'Общение с гостями' } },
  { id: 'assistant', category: 'guest', price: 25, includedIn: ['growth', 'scale'], name: { en: 'AI room finder', de: 'KI-Zimmersuche', ru: 'AI-подбор номера' } },
];

const descriptions: Record<string, NonNullable<SubscriptionModule['description']>> = {
  pms: { en: 'Keep reservations, guest records and room assignments together. Review stay dates, booking status and room availability from the back office.', de: 'Reservierungen, Gästedaten und Zimmerzuweisungen an einem Ort. Aufenthaltsdaten, Buchungsstatus und Verfügbarkeit in der Verwaltung prüfen.', ru: 'Бронирования, карточки гостей и назначение номеров в одном месте. Просматривайте даты проживания, статус брони и доступность номеров в админке.' },
  'front-desk': { en: 'Plan arrivals and departures on the room calendar. Open reservations, update stay status and move bookings between available rooms.', de: 'Anreisen und Abreisen im Zimmerkalender planen. Reservierungen öffnen, Aufenthaltsstatus ändern und Buchungen in verfügbare Zimmer verschieben.', ru: 'Планируйте заезды и выезды на календаре номеров. Открывайте брони, меняйте статус проживания и переносите бронирования между свободными номерами.' },
  accounting: { en: 'Review booking payments, invoices and financial statistics. Inspect invoice items, services and recorded payments, then print an invoice preview. Demo invoices have no fiscal standing.', de: 'Zahlungen, Rechnungen und Finanzstatistiken prüfen. Positionen, Leistungen und erfasste Zahlungen ansehen und Rechnungsvorschauen drucken. Demo-Rechnungen sind nicht steuerlich gültig.', ru: 'Просматривайте платежи, инвойсы и финансовую статистику. Проверяйте позиции проживания, услуги и зарегистрированные платежи, печатайте инвойсы. Демо-инвойсы не имеют фискальной силы.' },
  housekeeping: { en: 'Track room cleaning status and assign housekeeping tasks. Give reception visibility into which rooms are ready for arriving guests.', de: 'Reinigungsstatus verfolgen und Aufgaben zuweisen. Die Rezeption sieht, welche Zimmer für anreisende Gäste bereit sind.', ru: 'Следите за статусом уборки номеров и назначайте задачи сотрудникам. Ресепшен видит, какие номера готовы к заселению.' },
  orders: { en: 'Create food and service orders and link them to a reservation. Track delivery, due dates and payment status. Completed linked orders can appear in invoice details.', de: 'Essens- und Servicebestellungen mit Reservierungen verknüpfen. Lieferung, Termine und Zahlungsstatus verfolgen. Abgeschlossene Bestellungen können in Rechnungsdetails erscheinen.', ru: 'Создавайте заказы еды и услуг с привязкой к бронированию. Контролируйте доставку, сроки и оплату. Выполненные связанные заказы могут отображаться в детализации инвойса.' },
  'booking-engine': { en: 'Let guests search rooms, select dates and extras, enter their details and complete a demo booking directly on your hotel website. Real payment processing is not enabled.', de: 'Gäste suchen Zimmer, wählen Daten und Extras und schließen eine Demo-Direktbuchung auf der Hotelwebsite ab. Echte Zahlungsabwicklung ist nicht aktiviert.', ru: 'Гости выбирают номера, даты и дополнительные услуги, вводят свои данные и оформляют демо-бронирование прямо на сайте отеля. Реальная обработка платежей не подключена.' },
  channels: { en: 'Review distribution channels and their configuration in one workspace. This demo does not sync availability, rates or reservations with OTAs. Live connections require official partner APIs and separate setup.', de: 'Vertriebskanäle und Einstellungen zentral prüfen. Die Demo synchronisiert keine Verfügbarkeit, Preise oder Reservierungen mit OTAs. Live-Anbindungen benötigen offizielle Partner-APIs und separate Einrichtung.', ru: 'Просматривайте каналы продаж и их настройки в одном разделе. В демо доступность, тарифы и брони не синхронизируются с OTA. Для реального подключения нужны официальные API партнёров и отдельная настройка.' },
  rates: { en: 'Manage room rates and availability restrictions by date. Review rate plans and adjust the prices offered for a stay.', de: 'Zimmerpreise und Verfügbarkeitsbeschränkungen nach Datum verwalten. Tarifpläne prüfen und Aufenthaltspreise anpassen.', ru: 'Управляйте тарифами и ограничениями доступности по датам. Просматривайте тарифные планы и меняйте цены на проживание.' },
  communications: { en: 'Read guest conversations linked to reservations and reply from the hotel inbox. Track unread messages. External delivery depends on a separately configured messaging provider.', de: 'Buchungsbezogene Gästegespräche lesen und im Hotel-Posteingang beantworten. Ungelesene Nachrichten verfolgen. Externe Zustellung benötigt einen separat eingerichteten Anbieter.', ru: 'Читайте переписку гостей, связанную с бронированиями, и отвечайте из входящих отеля. Следите за непрочитанными сообщениями. Внешняя доставка зависит от отдельно настроенного провайдера.' },
  assistant: { en: 'Help guests find rooms based on their preferences and available catalog information. Suggestions support the search; availability and price must still be checked before booking.', de: 'Gästen passende Zimmer anhand ihrer Wünsche und des Katalogs vorschlagen. Verfügbarkeit und Preis müssen vor der Buchung erneut geprüft werden.', ru: 'Помогайте гостям подобрать номер по пожеланиям и данным каталога. Подсказки дополняют поиск; доступность и цену необходимо перепроверять перед бронированием.' },
};

export const subscriptionCatalog: SubscriptionCatalogPort = {
  async listModules() { return modules.map((item) => ({ ...item, includedIn: [...item.includedIn], name: { ...item.name }, description: { ...descriptions[item.id] } })); },
};
