/**
 * The one photo every sample guest document carries: a synthetic
 * 480×300 PNG that says so on its face ("TEST FIXTURE — NOT A VALID
 * DOCUMENT", a made-up MRZ), generated once and inlined so the Worker
 * and the Node build alike can seed it without reading a file. Never a
 * real identity document — see docs/GUEST_DOCUMENTS.md.
 */
const SAMPLE_DOCUMENT_PNG_BASE64 = [
  'iVBORw0KGgoAAAANSUhEUgAAAeAAAAEsCAIAAACUnPcNAAAHMklEQVR42u3dO3ITQRRAUa9DS2E1DolYn2JHXgoZARsgoIrEhao/',
  '773p7jmuE1B2azTT0lzDfMTb8/0bAAt6MwUAAg2AQAMINAACDSDQAAg0AAININAACDSAQAMg0AAINIBAAyDQAAINgEADCDQAAg2A',
  'QAMINACBgf796ycACxJoAIEGQKABBBoAgQYQaAAEGgCBBhBoAAQaQKABEGgABBpAoAEQaACBBkCgAQQaAIEGQKABBBqAFQP9mPjK',
  'WM7MMrPX56R57t3eU9cn+/VCoAVaoAVaoBFogRZogRZoBFqgBVqgcZKwbweIGp+9nKuWv8t2nTr+quWAQAu0QAs0Ai3QAi3QAo1A',
  'C7RACzQCLdACXRcpgUagBVqgBVqgEWiBFmiBBoEWaIEWaAQ6a4eJupg/46aAFQK98nZdtZzdb1SRJARaoAVaoBFogRZogRZoBFqg',
  'BVqgEeg9ThJaTycJM9Z5l/cJAi3QAi3QAo1AC7RACzQCLXwCLdACjUAL9AmBvvOHJUWNAYEWaIEWaARaoAVaoAUagbaeAi3QCPS6',
  'N6pk32hwaqBX+09as09aztxgUnnDi6Aj0AIt0AKNQAu0QAu0QCPQAi3QAo1AAyDQAAINgEADINAAAg2AQAMINAACDYBAAwg0AAIN',
  'INAACDSAQJsCAIEG4IpA//j+/tfYmH8/+qprcMvDJzew4Ckq5zBqEl486SIvU9f05j1q7FWefNTY61XwXAi0QAu0QAu0QAu0QAu0',
  'QAv0yoHuemtOJmkyNwXRLHiuvEdVzs+pc5iXv64fFezLlXulQAu0uAi0QAu0QAu0QAu0QFN8DHrsOwIt0GfPYdRzRe1fUc8u0AIt',
  '0AIt0AIt0AItLgIt0AJ9h8vswi/ouSTQBRcPrXYplUAfE+ioCwHHrj7UWYEWaIEWaIEWaIEWaIEWaIG+w52EjkE7Bi3QZ6yhQAu0',
  'QAu0QAu0QAu0uAi0QAu0QAv05EQJ9K3uJBRogRZogRZogRZogRZogRZogWbNQLdcDxT17BsFumBXyftkZ58HveCnSBd8HrRAC7RA',
  'C7RAC7RAC7RAC7RAC/QxgQZAoAEEGgCBBkCgAQQaAIEGEGgABBpAoAEQaAAEGkCgARBoAIEGQKABEGgAgQZAoAEEGgCBBkCgAQQa',
  'AIEGEGgABBpAoAEQaAAEGkCgARBoAIHu82j46nrUi8EtqxG1YuGTMLbkqAkfm/m8Vznq9Zp8R4U/KupVRqAFWqAFWqARaIEWaIGG',
  'skBPhmwytV0/GnuugtnIm/kdZ2O17YoaAwIt0AIt0Ai0QAu0QAs0Ah3+HYEWaIFGoAVaoAUaBFqgBVqgEeiyy5vCA73IZXbLXtcY',
  'flnkJZe+FVyCKdAItEALtEAj0AIt0AIt0Jwd6GWPGK52/HTHo/+V67PaWQ2BRqAFWqAFGgRaoAVaoBFogRbo7QI9thoCjUALtEAL',
  'NAIt0AIt0ALNSXcSVl4UVbnDh3+WcfjnQVeGbJEL5sIv6XMnIQIt0AIt0CDQAi3QAo1AAyDQAAINgEADINAAAg2AQAMINAACDSDQ',
  'AAg0AAININAACDSAQAMg0AAINIBAAyDQAAINgEADINAAAg2AQAMINAACDSDQAAg0AAININAACDSAQAMg0AAINIBAA3BpoD8/ngB8',
  'fjz9DRrA36ABEGgABBpAoAEQaACBBkCgAQQaAIEGQKABBBoAgQYQaAAEGoCsQD/+89X+2K9/fj2m5Rlb1md+OTPr3LKclrVtf2zv',
  'mLxtb3museVEbbsxGWMQaIEWaEEUaIHu2VHbczC//PZwzG/X65TUrE9emqN+ocZu19ivf2OkWaAFWqAF2hh2DvQK348NdPufVwvZ',
  '2C/XfbfLGGkWaIEWaIE2ht1OEvYe9Mj+/thpq7FA550kzNi1Xq9/7AnS9pO6M+8iY6RZoAVaoAXaGHY4xLHLIZGMk2AZ/8xf4RBH',
  'xrZXHn4xRqYFWqAFWqCNYc9Ar3CZ3R0CvctldhmBlkWZFmiBFmiBNkagTwz02Im73pNFYzcWXxXo1W53jroVfmy7XJYn0wIt0AIt',
  '0MYI9LmBBkCgAQQaAIEGQKABBBoAgQYQaAAEGkCgARBoAAQaQKABEGgAgWZVM/9J68zHut5znsc+1tW8GSPQdgCBFmiBFmh2C3TG',
  '980zslv/bhFogRYmgRZogUagBVqapVmgBVqgBVqgBRqBvtdJQjMju5V7ikALtEALtEALNALtEIdMy7RAC7RAC7RACzQCLdDItMvs',
  'EGiBFmiBZsdTWGNvHSfBBFqm3eqNQAu0eTNGoAFOIdAAAg2AQAMINAACDSDQAAg0AAININAACDSAQAMg0AAINIBAAyDQAAINgEAD',
  'CDQAAg2AQAMINAACDSDQAAg0AAININAACDSAQAMg0AACDYBAAyDQAAINgEADCDQAAg2AQAMINAACDSDQAAg0gECbAgCBBkCgAQQa',
  'gCR/ANPXVNV2WLJkAAAAAElFTkSuQmCC',
].join('');

export function sampleDocumentImage(): ArrayBuffer {
  const binary = atob(SAMPLE_DOCUMENT_PNG_BASE64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
  return bytes.buffer;
}
