import { expect, test } from '@playwright/test'

test('pricing calculator configures rooms, channels, modules and billing', async ({ page }) => {
  await page.goto('/pricing/modules/')
  await expect(page).toHaveURL(/\/pricing\/$/)
  await expect(page.getByRole('heading', { name: 'Build your direct-booking plan.' })).toBeVisible()

  await page.getByRole('tab', { name: /Boutique/ }).click()
  await expect(page.getByRole('tab', { name: /Boutique/ })).toHaveAttribute('aria-selected', 'true')
  await page.getByLabel('Rooms, exact number').fill('65')
  await page.getByLabel('Rooms, exact number').press('Enter')
  await page.getByLabel('Connected channels, exact number').fill('4')
  await page.getByLabel('Connected channels, exact number').press('Enter')

  await page.getByRole('button', { name: /Modules/ }).first().click()
  const included = page.getByRole('region', { name: /Modules/ })
  const optionalModule = page.getByRole('button', { name: /Housekeeping/ })
  await expect(optionalModule).toHaveAttribute('aria-pressed', 'false')
  await optionalModule.click()
  await expect(optionalModule).toHaveAttribute('aria-pressed', 'true')
  const summary = page.getByRole('complementary', { name: 'Price summary' })
  await expect(summary.getByText('Selected modules (1)')).toBeVisible()
  await expect(summary.getByText('Housekeeping')).toBeVisible()
  await optionalModule.click()
  await expect(summary.getByText('Selected modules (0)')).toBeVisible()

  await included.getByRole('button', { name: 'Review your price' }).click()
  await page.getByRole('group', { name: 'Billing period' }).getByRole('button', { name: 'Monthly' }).click()
  await expect(summary.getByText('Monthly')).toBeVisible()
  const monthlyAmount = await summary.locator('span[aria-live="polite"]').first().innerText()
  await page.getByRole('group', { name: 'Billing period' }).getByRole('button', { name: /Yearly/ }).click()
  await expect(summary.getByText('Yearly')).toBeVisible()
  expect(await summary.locator('span[aria-live="polite"]').first().innerText()).toBe(monthlyAmount)
  await expect(summary.getByText(/billed yearly/)).toBeVisible()
})

test('demo request is editable, required, keyboard dismissible and fits the viewport', async ({ page }) => {
  await page.goto('/pricing/?plan=group')
  await page.getByRole('button', { name: 'Continue to order' }).click()
  const dialog = page.getByRole('dialog', { name: 'Request final price and payment details' })
  await expect(dialog).toBeVisible()
  await expect(page.getByLabel('Name')).toBeFocused()
  await expect(page.getByLabel('Name')).toHaveAttribute('required', '')
  await expect(page.getByLabel('Email')).toHaveAttribute('required', '')
  await expect(page.getByLabel('Phone')).toHaveAttribute('required', '')
  const message = page.getByLabel('Message')
  await expect(message).toHaveValue(/Plan: Group/)
  await message.fill('Updated quote details\nPlease call in the afternoon.')
  await expect(message).toHaveValue('Updated quote details\nPlease call in the afternoon.')
  await dialog.getByRole('button', { name: 'Send request' }).focus()
  await page.keyboard.press('Tab')
  await expect(dialog.getByRole('button', { name: 'Close' })).toBeFocused()
  const box = await dialog.boundingBox()
  expect(box).not.toBeNull()
  expect(box!.x).toBeGreaterThanOrEqual(0)
  expect(box!.x + box!.width).toBeLessThanOrEqual(await page.evaluate(() => window.innerWidth))
  await page.keyboard.press('Escape')
  await expect(dialog).toBeHidden()
})
